"""empty message

Revision ID: 0279bf0ce97f
Revises: 417e77179e75
Create Date: 2024-03-28 16:45:16.893509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0279bf0ce97f'
down_revision = '417e77179e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breednotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_user', sa.String(), nullable=False))
        batch_op.drop_constraint('breednotes_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'auth0user', ['auth_user'], ['auth_user'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breednotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('breednotes_id_fkey', 'user', ['id'], ['id'])
        batch_op.drop_column('auth_user')

    # ### end Alembic commands ###
