"""empty message

Revision ID: 417e77179e75
Revises: 9e385cbd719f
Create Date: 2024-03-28 11:10:50.440314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417e77179e75'
down_revision = '9e385cbd719f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth0user',
    sa.Column('a_user', sa.Integer(), nullable=False),
    sa.Column('auth_user', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('a_user')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth0user')
    # ### end Alembic commands ###
