"""empty message

Revision ID: 7336ed814a5c
Revises: e21cbd7bfe2b
Create Date: 2024-03-14 11:55:44.463511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7336ed814a5c'
down_revision = 'e21cbd7bfe2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogapidict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogapidict', schema=None) as batch_op:
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
