"""empty message

Revision ID: 9e385cbd719f
Revises: fe8abf4eabb7
Create Date: 2024-03-23 10:33:23.287114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e385cbd719f'
down_revision = 'fe8abf4eabb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breednotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.String(), nullable=True))
        batch_op.drop_constraint('breednotes_user_token_fkey', type_='foreignkey')
        batch_op.drop_constraint('breednotes_breed_info_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_token')
        batch_op.drop_column('breed_info_id')

    with op.batch_alter_table('dogapidict', schema=None) as batch_op:
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dogapidict', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('breednotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_info_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('breednotes_breed_info_id_fkey', 'breedinfo', ['breed_info_id'], ['breed_info_id'])
        batch_op.create_foreign_key('breednotes_user_token_fkey', 'user', ['user_token'], ['token'])
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
