"""empty message

Revision ID: bedeabdcdb68
Revises: 7336ed814a5c
Create Date: 2024-03-23 10:25:22.529358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bedeabdcdb68'
down_revision = '7336ed814a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breednotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.String(), nullable=False))
        batch_op.drop_constraint('breednotes_breed_info_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('breednotes_user_token_fkey', type_='foreignkey')
        batch_op.drop_column('user_token')
        batch_op.drop_column('breed_info_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breednotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed_info_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_token', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('breednotes_user_token_fkey', 'user', ['user_token'], ['token'])
        batch_op.create_foreign_key('breednotes_breed_info_id_fkey', 'breedinfo', ['breed_info_id'], ['breed_info_id'])
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###
