"""empty message

Revision ID: cee2473cfee3
Revises: 
Create Date: 2024-01-21 13:11:45.568211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cee2473cfee3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('breed_group', sa.String(length=100), nullable=True),
    sa.Column('life_span', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('height', sa.String(length=100), nullable=True),
    sa.Column('bred_for', sa.String(length=200), nullable=True),
    sa.Column('temperament', sa.String(length=500), nullable=True),
    sa.Column('reference_image_id', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dog')
    # ### end Alembic commands ###
