"""empty message

Revision ID: efb6a67f56c7
Revises: 
Create Date: 2024-02-14 11:13:04.648009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb6a67f56c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('breedinfo',
    sa.Column('breed_id', sa.String(length=36), nullable=False),
    sa.Column('breed_name', sa.String(length=100), nullable=True),
    sa.Column('breed_group', sa.String(length=100), nullable=True),
    sa.Column('life_span', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.String(length=100), nullable=True),
    sa.Column('height', sa.String(length=100), nullable=True),
    sa.Column('bred_for', sa.String(length=200), nullable=True),
    sa.Column('temperament', sa.String(length=500), nullable=True),
    sa.Column('reference_image_id', sa.String(length=50), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('breed_id')
    )
    op.create_table('breednotes',
    sa.Column('breedNotes_Id', sa.String(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breedinfo.breed_id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('breedNotes_Id')
    )

    op.create_table('dogapidict',
    sa.Column('dict_id', sa.String(), nullable=False),
    sa.Column('dict_breed_name', sa.String(), nullable=True),
    sa.Column('dict_breed_id', sa.Integer(), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('dict_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('breednotes')
    op.drop_table('breedinfo')
    op.drop_table('user')
    # ### end Alembic commands ###
